Calendar
Buffik/rs-clone pull request #10
Opened 2023-02-16 21:57 UTC by olegpl1993

2023-02-16 22:13 UTC, Buffik requested changes

2023-02-16 22:13 UTC, Buffik commented on src/pages/CalendarPage/CalendarPage.tsx
> +  };
Статичные переменные, а также объявление их интерфейсов лучше вынести за пределы компонента. При каждом рендере компонента будут заново создаваться их инстансы

2023-02-16 22:13 UTC, Buffik commented on src/pages/CalendarPage/CalendarPage.tsx
> +              (month, index) => <MenuItem key={Math.random()} value={index}>{month}</MenuItem>,
в качестве значения ключа (key) в данном случае лучше использовать наименование месяца, так как мы со 100% вероятностью можем гарантировать, что они будут уникальными при каждом рендере

2023-02-17 00:57 UTC, dinara-n commented on src/components/Calendar/Calendar.tsx
> +                      <div>{day && taskData[day - 1] ? taskData[day - 1].missed : 0}</div>
Предлагаю показывать количество задач, только когда их больше 0
![image](https://user-images.githubusercontent.com/33234957/219521554-aca22d92-2c18-44d6-b598-11d79e411332.png)

```suggestion
                    {day && !!taskData[day - 1]?.future
                      && (
                        <div className={styles.future}>
                          <div>{text[languageState].future}:</div>
                          <div>{taskData[day - 1].future}</div>
                        </div>
                      )}
                    {day && !!taskData[day - 1]?.complete
                      && (
                        <div className={styles.complete}>
                          <div>{text[languageState].complete}:</div>
                          <div>{taskData[day - 1].complete}</div>
                        </div>
                      )}

                    {day && !!taskData[day - 1]?.missed
                      && (
                        <div className={styles.missed}>
                          <div>{text[languageState].missed}:</div>
                          <div>{taskData[day - 1].missed}</div>
                        </div>
                      )}
```

2023-02-17 01:03 UTC, dinara-n commented on src/components/Calendar/calendarHelper.ts
> +  for (let i = 0; i < (daysInMonth + monthStartsOn) / DAYS_IN_WEEK; i += 1) {
(daysInMonth + monthStartsOn) / DAYS_IN_WEEK лучше вынести в отдельную переменную, иначе это выражение будет вычисляться заново на каждой итерации цикла

2023-02-17 01:20 UTC, dinara-n commented on src/api/api.ts
> +export const API_URL = 'https://rsclone-backend-production.up.railway.app/';
Я вчера дала не совсем верную ссылку. Правильно так:
```suggestion
export const API_URL = 'https://rsclone-backend-production.up.railway.app';
```

2023-02-17 18:49 UTC, olegpl1993 commented on src/pages/CalendarPage/CalendarPage.tsx
> +              (month, index) => <MenuItem key={Math.random()} value={index}>{month}</MenuItem>,
исправил

2023-02-17 19:42 UTC, merged